leftnav:
- identifier: 4c8c288d-71cd-0cf6-e062-325be8917229
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 235990a5-1e51-8953-1fed-b90051a331ad
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 04230dbb-7c9e-8330-4ad7-8446b74acca0
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 3970d0e3-55d6-4209-7d13-ef4e7e2f4d15
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 00f8cfef-3306-2d6e-1455-3ad862a56ae6
  name: Exams
  url: /pages/exams
  weight: 50
- identifier: 5c7f29c1-d600-f596-e62d-e84b61cb25d8
  name: Study Materials
  url: /pages/study-materials
  weight: 60
